# Generated by Django 5.0.3 on 2024-04-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('number_of_keys', models.IntegerField()),
                ('type', models.CharField(choices=[('grand', 'Grand'), ('upright', 'Upright'), ('digital', 'Digital'), ('electronic', 'Electronic')], max_length=11)),
                ('condition', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
