# Generated by Django 5.0.3 on 2024-04-04 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maintenancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('years_of_experience', models.IntegerField()),
                ('style', models.CharField(choices=[('classical', 'Classical'), ('jazz', 'Jazz'), ('rock and roll:', 'Rock and Roll'), ('pop', 'Pop'), ('ragtime', 'Ragtime'), ('boogie-Woogie', 'Boogie-Woogie'), ('contemporary', 'Contemporary')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Maintenance Date'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='technician',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
