# Generated by Django 5.0.3 on 2024-04-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_performer_maintenancerecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='style',
            field=models.CharField(choices=[('classical', 'Classical'), ('jazz', 'Jazz'), ('rock and roll', 'Rock and Roll'), ('pop', 'Pop'), ('ragtime', 'Ragtime'), ('boogie-Woogie', 'Boogie-Woogie'), ('contemporary', 'Contemporary')], max_length=15),
        ),
    ]
