# Generated by Django 5.0.3 on 2024-04-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_performer_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='performer',
            field=models.ManyToManyField(to='main_app.performer'),
        ),
    ]
